#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

# Install Python wrappers:
cmake -DCMAKE_INSTALL_PREFIX="$SPKG_LOCAL" .
make
make install


# Install elk itself:

cat > make.inc << EOF
MAKE = make
F90 = gfortran
F90_OPTS = -O3 -funroll-loops -ffast-math
F77 = gfortran
F77_OPTS = -O3 -funroll-loops -ffast-math
AR = ar
LIB_SYS =

if [ "$(uname)" = "Darwin" ]; then
    LIB_LPK = -framework Accelerate
else
    LIB_LPK = lapack.a blas.a
fi

LIB_FFT = fftlib.a
EOF

# Elk doesn't compile well in parallel:
unset MAKEFLAGS
make -f Makefile.orig

# Install executables:
cp src/elk "$SPKG_LOCAL"/bin
cp src/spacegroup/spacegroup "$SPKG_LOCAL"/bin
cp src/eos/eos "$SPKG_LOCAL"/bin
